name: '🐛 Bug Report'
description: Report a reproducible bug.
labels:
- possible-bug
- needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place.
        Please read and follow the instructions before submitting an issue:
  - type: markdown
    attributes:
      value: |
        - If you have found a security issue [please submit it here](https://hackerone.com/github)
        - If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
        - If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)
        - Read all our documentation, especially the [README](https://github.com/heliomarpm/action-electron-builder/blob/master/README.md). It may contain information that helps you solve your issue.
        - Ensure your issue isn't already [reported](https://github.com/heliomarpm/action-electron-builder/issues?utf8=%E2%9C%93&q=is%3Aissue).
        - Ensure it isn't already fixed in the latest action-electron-builder version.
  - type: markdown
    attributes:
      value: '⚠️👆 Feel free to these instructions before submitting the issue 👆⚠️'
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context/Screenshots'
      description: Add any other context about the problem here. If applicable, add screenshots to help explain.
      render: bash
    validations:
      required: false
