name: Lint

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**/*.sh"
      - "**/.*"
      - "**/_*"
      - "**/*.txt"
      - "**/*.adoc"
      - "**/*.md"
      - ".github/**"
      - "!.github/workflows/lint.yml"
  pull_request:
    paths-ignore:
      - "**/*.sh"
      - "**/.*"
      - "**/_*"
      - "**/*.txt"
      - "**/*.adoc"
      - "**/*.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20.12.2"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run format
